services:
  - type: web
    name: audiotextly
    env: python
    plan: free
    buildCommand: |
       chmod +x backend/start.sh
       pip install -r backend/requirements.txt
    startCommand: bash backend/start.sh
    pythonVersion: 3.10
    envVars:
      - key: WHISPER_MODEL
        value: tiny
    autoDeploy: true
    buildFilter:
      paths:
        - backend/**